#!/bin/sh

OBJECTS=`git list-all-objects`

for sha1 in $OBJECTS; do
    TYP=`git cat-file -t $sha1`
    if [ "$1" ]; then
        if [ $TYP == "$1" ]; then
            echo "===================================================="
            echo $TYP $sha1;
            echo
            git cat-file -p $sha1;
        fi
    else
        echo $TYP $sha1;
    fi


done;