#!/bin/sh

stat() {
    echo -n Number of revisions:;
    git log --oneline | wc -l;
    echo -n Number of developers:;
    git shortlog -s | wc -l;
    echo -n Number of days:;
    git days | wc -l;
    echo -n The working directory:;
    du -h -s --exclude=.git;
    echo -n The git directory:;
    du -h -s .git;
    echo -n Number of files in the working dir:;
    git ls-files | wc -l;
};

stat

